-- Migration: Create Product Data Sheets Table
-- Description: Stores AI-generated and editable product documentation (SDS, spec sheets, etc.)
-- Author: MuRP Team
-- Date: 2025-11-06
-- Phase: 1.3 - Core Infrastructure

-- ============================================================================
-- Product Data Sheets Table
-- ============================================================================
-- Stores comprehensive product documentation generated by AI and editable by users
-- Supports multiple document types: SDS, spec sheets, product info, compliance docs

CREATE TABLE IF NOT EXISTS product_data_sheets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Associations
  bom_id UUID NOT NULL,                      -- Always linked to a BOM
  label_id UUID,                             -- Optional link to primary label
  -- Foreign keys will be added after tables exist

  -- Document information
  document_type TEXT NOT NULL,               -- 'sds', 'spec_sheet', 'product_info', 'compliance_doc'
  title TEXT NOT NULL,
  version NUMERIC DEFAULT 1.0,
  description TEXT,

  -- AI-generated content (structured as JSONB for flexibility and editability)
  content JSONB NOT NULL,
  /*
    Example structure for comprehensive product data sheet:
    {
      "productIdentification": {
        "productName": "Organic Fertilizer 10-5-8",
        "sku": "FERT-1058-50LB",
        "barcode": "123456789012",
        "manufacturer": "MuRP Manufacturing",
        "manufacturerAddress": "123 Farm Road, Portland, OR 97201",
        "emergencyPhone": "(800) 555-1234",
        "productUse": "Agricultural fertilizer for organic farming"
      },
      "composition": {
        "ingredients": [
          {
            "name": "Blood Meal",
            "percentage": "15%",
            "casNumber": "68475-43-4",
            "function": "Nitrogen source"
          },
          {
            "name": "Bone Meal",
            "percentage": "10%",
            "casNumber": null,
            "function": "Phosphorus source"
          }
        ],
        "guaranteedAnalysis": {
          "totalNitrogen": "10.0%",
          "availablePhosphate": "5.0%",
          "soluablePotash": "8.0%",
          "calcium": "2.0%",
          "sulfur": "1.5%",
          "derivedFrom": "Blood meal, bone meal, kelp meal, potassium sulfate"
        }
      },
      "hazardsIdentification": {
        "hazardClassification": "Not classified as hazardous",
        "labelElements": ["Keep out of reach of children"],
        "warningStatements": ["May cause skin irritation in sensitive individuals"],
        "firstAidMeasures": {
          "inhalation": "Move to fresh air. If symptoms persist, seek medical attention.",
          "skinContact": "Wash thoroughly with soap and water. If irritation persists, seek medical attention.",
          "eyeContact": "Rinse cautiously with water for several minutes. If irritation persists, seek medical attention.",
          "ingestion": "Do not induce vomiting. Rinse mouth. Seek medical attention if symptoms occur."
        }
      },
      "storageAndHandling": {
        "storageConditions": "Store in a cool, dry place away from direct sunlight",
        "temperatureRange": "50-90°F (10-32°C)",
        "shelfLife": "24 months from date of manufacture",
        "handlingPrecautions": ["Avoid breathing dust", "Wear gloves when handling", "Wash hands after use"],
        "incompatibilities": "Avoid contact with strong oxidizing agents"
      },
      "regulatoryInformation": {
        "stateRegistrations": [
          {
            "state": "California",
            "registrationNumber": "CA-12345",
            "expirationDate": "2025-12-31",
            "status": "current"
          },
          {
            "state": "Oregon",
            "registrationNumber": "OR-67890",
            "expirationDate": "2026-06-30",
            "status": "current"
          }
        ],
        "certifications": [
          "OMRI Listed",
          "USDA Organic Certified",
          "CDFA Registered"
        ],
        "epaRegistration": null,
        "tsca": "All ingredients are listed on the TSCA inventory"
      },
      "technicalData": {
        "applicationRates": {
          "vegetables": "1-2 cups per plant",
          "trees": "3-5 cups per tree",
          "lawns": "10 lbs per 1000 sq ft"
        },
        "directions": "Apply evenly around base of plant. Water thoroughly after application. For best results, apply in early spring or fall.",
        "compatibility": "Compatible with most organic fertilizers and soil amendments. Do not mix with lime.",
        "physicalProperties": {
          "appearance": "Brown granular powder",
          "odor": "Earthy, organic",
          "pH": "6.5-7.5 (in water)",
          "solubility": "Partially soluble in water",
          "density": "45 lbs/cubic foot"
        }
      },
      "manufacturingInformation": {
        "bomComponents": [
          {"sku": "RM-001", "name": "Blood Meal", "quantity": 7.5, "unit": "lbs"},
          {"sku": "RM-002", "name": "Bone Meal", "quantity": 5, "unit": "lbs"},
          {"sku": "RM-003", "name": "Kelp Meal", "quantity": 3, "unit": "lbs"}
        ],
        "packagingSpecs": {
          "bagType": "Multi-wall paper bag with poly liner",
          "labelType": "Direct print on bag",
          "netWeight": "50 lbs (22.7 kg)"
        },
        "yieldInformation": {
          "batchSize": "1000 lbs",
          "unitsPerBatch": 20,
          "manufactureDate": "Printed on package"
        }
      },
      "customSections": [
        {
          "title": "Environmental Impact",
          "content": "This product is derived from natural, renewable resources and is biodegradable. When used as directed, it poses minimal risk to the environment."
        },
        {
          "title": "Quality Assurance",
          "content": "Each batch is tested for nutrient content and heavy metal contamination to ensure compliance with organic standards."
        }
      ]
    }
  */

  -- PDF generation
  pdf_url TEXT,                              -- Generated PDF stored in Supabase storage
  pdf_generated_at TIMESTAMPTZ,
  pdf_file_size BIGINT,                      -- bytes

  -- Document status
  status TEXT DEFAULT 'draft',               -- 'draft', 'review', 'approved', 'published', 'archived'

  -- Approval workflow
  approved_by UUID,                          -- References users(id)
  approved_at TIMESTAMPTZ,
  approval_notes TEXT,

  -- Generation tracking
  is_ai_generated BOOLEAN DEFAULT true,
  ai_model_used TEXT,                        -- e.g., 'gemini-1.5-pro', 'gpt-4'
  generation_prompt TEXT,                    -- The prompt used to generate content

  -- Edit tracking
  last_edited_by UUID,                       -- References users(id)
  edit_count INTEGER DEFAULT 0,
  edit_history JSONB,
  /*
    Example edit history:
    [
      {
        "timestamp": "2025-11-06T10:30:00Z",
        "user_id": "uuid",
        "action": "create",
        "changes": "Initial AI generation"
      },
      {
        "timestamp": "2025-11-06T14:45:00Z",
        "user_id": "uuid",
        "action": "edit",
        "section": "storageAndHandling",
        "changes": "Updated temperature range"
      }
    ]
  */

  -- Publishing
  published_at TIMESTAMPTZ,
  published_version NUMERIC,

  -- Metadata
  tags TEXT[],                               -- For categorization and search
  notes TEXT,

  -- Audit trail
  created_by UUID,                           -- References users(id)
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- Indexes for Performance
-- ============================================================================

CREATE INDEX idx_pds_bom_id ON product_data_sheets(bom_id);
CREATE INDEX idx_pds_label_id ON product_data_sheets(label_id) WHERE label_id IS NOT NULL;
CREATE INDEX idx_pds_document_type ON product_data_sheets(document_type);
CREATE INDEX idx_pds_status ON product_data_sheets(status);
CREATE INDEX idx_pds_created_at ON product_data_sheets(created_at DESC);
CREATE INDEX idx_pds_created_by ON product_data_sheets(created_by);
CREATE INDEX idx_pds_version ON product_data_sheets(bom_id, version DESC);

-- GIN index for JSONB content (enables fast queries on JSON fields)
CREATE INDEX idx_pds_content ON product_data_sheets USING GIN (content);
CREATE INDEX idx_pds_edit_history ON product_data_sheets USING GIN (edit_history);

-- Full-text search on title and description
CREATE INDEX idx_pds_title_search ON product_data_sheets USING GIN (to_tsvector('english', title));
CREATE INDEX idx_pds_tags ON product_data_sheets USING GIN (tags);

-- ============================================================================
-- Constraints
-- ============================================================================

ALTER TABLE product_data_sheets ADD CONSTRAINT pds_document_type_check
  CHECK (document_type IN ('sds', 'spec_sheet', 'product_info', 'compliance_doc', 'custom'));

ALTER TABLE product_data_sheets ADD CONSTRAINT pds_status_check
  CHECK (status IN ('draft', 'review', 'approved', 'published', 'archived'));

ALTER TABLE product_data_sheets ADD CONSTRAINT pds_version_positive
  CHECK (version > 0);

-- ============================================================================
-- Row Level Security (RLS)
-- ============================================================================

ALTER TABLE product_data_sheets ENABLE ROW LEVEL SECURITY;

-- Users can view all product data sheets (within their organization)
CREATE POLICY pds_select_policy ON product_data_sheets
  FOR SELECT
  TO authenticated
  USING (true);  -- Adjust for multi-tenant

-- Users can create product data sheets
CREATE POLICY pds_insert_policy ON product_data_sheets
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = created_by OR created_by IS NULL);

-- Users can update product data sheets they created or are assigned to edit
CREATE POLICY pds_update_policy ON product_data_sheets
  FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = created_by
    OR auth.uid() = last_edited_by
    OR status = 'draft'
  );

-- Only creators can delete drafts
CREATE POLICY pds_delete_policy ON product_data_sheets
  FOR DELETE
  TO authenticated
  USING (auth.uid() = created_by AND status = 'draft');

-- ============================================================================
-- Triggers
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_pds_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  NEW.edit_count = OLD.edit_count + 1;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_pds_updated_at
  BEFORE UPDATE ON product_data_sheets
  FOR EACH ROW
  EXECUTE FUNCTION update_pds_updated_at();

-- ============================================================================
-- Helper Functions
-- ============================================================================

-- Function to get all data sheets for a BOM
CREATE OR REPLACE FUNCTION get_data_sheets_by_bom(p_bom_id UUID)
RETURNS TABLE (
  id UUID,
  document_type TEXT,
  title TEXT,
  version NUMERIC,
  status TEXT,
  created_at TIMESTAMPTZ,
  pdf_url TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    pds.id,
    pds.document_type,
    pds.title,
    pds.version,
    pds.status,
    pds.created_at,
    pds.pdf_url
  FROM product_data_sheets pds
  WHERE pds.bom_id = p_bom_id
  ORDER BY pds.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get latest version of a document type for a BOM
CREATE OR REPLACE FUNCTION get_latest_data_sheet(
  p_bom_id UUID,
  p_document_type TEXT
)
RETURNS TABLE (
  id UUID,
  version NUMERIC,
  content JSONB,
  status TEXT,
  pdf_url TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    pds.id,
    pds.version,
    pds.content,
    pds.status,
    pds.pdf_url
  FROM product_data_sheets pds
  WHERE pds.bom_id = p_bom_id
    AND pds.document_type = p_document_type
  ORDER BY pds.version DESC
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to publish a data sheet (increments version, sets published status)
CREATE OR REPLACE FUNCTION publish_data_sheet(
  p_data_sheet_id UUID,
  p_user_id UUID
)
RETURNS UUID AS $$
DECLARE
  v_new_version NUMERIC;
  v_bom_id UUID;
  v_document_type TEXT;
  v_title TEXT;
  v_content JSONB;
  v_new_id UUID;
BEGIN
  -- Get current data sheet info
  SELECT bom_id, document_type, title, content, version + 0.1
  INTO v_bom_id, v_document_type, v_title, v_content, v_new_version
  FROM product_data_sheets
  WHERE id = p_data_sheet_id;

  -- Create new published version
  INSERT INTO product_data_sheets (
    bom_id,
    document_type,
    title,
    version,
    content,
    status,
    published_at,
    published_version,
    approved_by,
    approved_at,
    created_by
  ) VALUES (
    v_bom_id,
    v_document_type,
    v_title,
    v_new_version,
    v_content,
    'published',
    NOW(),
    v_new_version,
    p_user_id,
    NOW(),
    p_user_id
  ) RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON TABLE product_data_sheets IS 'Stores AI-generated and editable product documentation (SDS, spec sheets, etc.)';
COMMENT ON COLUMN product_data_sheets.content IS 'JSONB structure containing all document sections (identification, composition, hazards, storage, regulatory, technical, manufacturing)';
COMMENT ON COLUMN product_data_sheets.edit_history IS 'JSONB array tracking all edits made to the document';
COMMENT ON COLUMN product_data_sheets.document_type IS 'Type of document: sds, spec_sheet, product_info, compliance_doc, custom';
COMMENT ON COLUMN product_data_sheets.status IS 'Document workflow status: draft, review, approved, published, archived';

-- ============================================================================
-- Grants
-- ============================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON product_data_sheets TO authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;
